### ISSUE TITLE
文章显示错误

### ISSUE THREAD

**Issue by argvchs** [LynxCatTheThird/web-v2#3]
在 Chrome DevTools 选择设备为 Surface Pro 7 时显示如下

<img src="https://user-images.githubusercontent.com/64528288/210932891-949f92d8-cf98-46ce-b5e8-bc39db95a98b.png" width="500px">

但我的是对的

<img src="https://user-images.githubusercontent.com/64528288/210932908-b7f99a82-5201-4152-ab52-c198efb5e97b.png" width="500px">

**Comment by argvchs** [comment]
还有就是 `filter: blur()` 模糊效果非常卡（真的很卡），建议去掉

**Comment by LynxCatTheThird** [comment]
Surface Pro 7 超出去是因为我把 ```article``` 的 ```width``` 设成了 ```1100px```，所以爆掉了

模糊效果我这儿并不怎么卡，可能因人而异……

**Comment by argvchs** [comment]
滚动时晃动鼠标就会很卡
