### ISSUE TITLE
ParticleX 更新

### ISSUE THREAD

**Issue by argvchs** [LynxCatTheThird/web-v2#4]
这些是最近更改的：

- [x] 优化搜索，不需要安装插件（但是只能搜索 Title 了）

- [x] 整合搜索和文章加密到 `particlex.js` 里，去除 `searcher.js` 和 `cryptor.js`

- [x] 添加文章置顶

- [x] 为 `hexo new page` 生成的页面添加评论功能，例如 `about`，但是 `archives` `categories` `tags` 除外

- [x] 修复 `word-wrap` `word-break` 断句问题

- [x] 修复小尺寸屏幕 Tags 如果过多堆在一起的问题

- [x] 调整小尺寸屏幕导航栏文字，自动转换为大写（和大尺寸屏幕统一）

- [x] 调整主页卡片名称，不自动转换为大写

- [x] 调整主页友链样式

- [x] 修复主页图标链接或友链为空时，有一条横线的问题

- [x] 主页 Description 不使用列表进行换行（因为都支持 Markdown 了直接 `\n` 就可以了）

- [x] 修改 README，Description 参数使用多行字符串语法

**Comment by LynxCatTheThird** [comment]
更新完成力
